language: python
python:
- 2.7
before_install:
- sudo apt-get -y update
- sudo apt-get -y install libatlas-dev libblas-dev g++ gcc gfortran libffi-dev uuid make libssl-dev python-dev python-numpy
- pip install pip --upgrade
- sudo apt-get -y install ruby ruby-dev make rpm rubygems
- gem install fpm --no-ri --no-rdoc
script:
- make .rpm
- make .deb
deploy:
  - provider: packagecloud
    repository: metrilyx
    username: metrilyx
    local-dir: build/ubuntu
    dist: ubuntu/trusty
    skip_cleanup: true
  - provider: packagecloud
    repository: metrilyx
    username: metrilyx
    local-dir: build/el
    dist: el/7
    skip_cleanup: true
notifications:
  slack:
    rooms:
    - ticketmaster:E5CXbILXq45Y5LYcsO8BD3B3#metrilyx
